#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71C636695B147849 (dict-upload@aspell.net)
#
Name     : aspell-de
Version  : 20161207.7.0
Release  : 1
URL      : https://ftp.gnu.org/gnu/aspell/dict/de/aspell6-de-20161207-7-0.tar.bz2
Source0  : https://ftp.gnu.org/gnu/aspell/dict/de/aspell6-de-20161207-7-0.tar.bz2
Source1 : https://ftp.gnu.org/gnu/aspell/dict/de/aspell6-de-20161207-7-0.tar.bz2.sig
Summary  : German dictionary for aspell
Group    : Development/Tools
License  : GPL-2.0
Requires: aspell-de-license = %{version}-%{release}
BuildRequires : aspell-dev
Patch1: 0001-configure-ignore-unknown-options.patch

%description
GNU Aspell 0.60 German Dictionary Package
Version 20161207-7-0
2019-07-23
Maintained By:
Kevin Atkinson <kevina at gnu org>
Roland Rosenfeld <roland at debian org>
Wordlist URL: https://packages.debian.org/testing/aspell-de
Source URL: https://www.j3e.de/ispell/igerman98/

%package license
Summary: license components for the aspell-de package.
Group: Default

%description license
license components for the aspell-de package.


%prep
%setup -q -n aspell6-de-20161207-7-0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570025679
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1570025679
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aspell-de
cp Copyright %{buildroot}/usr/share/package-licenses/aspell-de/Copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/de-common.rws
/usr/lib64/aspell-0.60/de.dat
/usr/lib64/aspell-0.60/de.multi
/usr/lib64/aspell-0.60/de_AT-only.rws
/usr/lib64/aspell-0.60/de_AT.multi
/usr/lib64/aspell-0.60/de_CH-only.rws
/usr/lib64/aspell-0.60/de_CH.multi
/usr/lib64/aspell-0.60/de_DE-only.rws
/usr/lib64/aspell-0.60/de_DE.multi
/usr/lib64/aspell-0.60/de_affix.dat
/usr/lib64/aspell-0.60/de_phonet.dat
/usr/lib64/aspell-0.60/deutsch.alias
/usr/lib64/aspell-0.60/german.alias

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aspell-de/Copyright
